### ISSUE TITLE
SVG with default XML processing instructions

### ISSUE THREAD

**Issue by kosaj** [jaywcjlove/svgtofont#179]
Ilustrator exports SVG with default XML processing instructions **_<?xml version="1.0" encoding="UTF-8"?>_** that will throw given error when svg is parsed.

SvgToFont:CLI:ERR: Error: Unmatched selector: ="1.0" encoding="UTF-8"?><svg id="Warstwa_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60"><defs><style>.cls-1{fill:#000100;}.cls-2{isolation:isolate;}</style></defs><g class="cls-2"><path class="cls-1" d="M31.76,27.71h8.33v3.3h-8.33v8.68h-3.51v-8.68h-8.33v-3.3h8.33v-8.02h3.51v8.02Z"/></g></svg>
    at parse (\node_modules\css-what\lib\commonjs\parse.js:85:15)
    at Object.select (\node_modules\cheerio-select\lib\index.js:191:68)
    at LoadedCheerio.find (\node_modules\cheerio\lib\api\traversing.js:90:30)
    at initialize (\node_modules\cheerio\lib\load.js:156:34)
    at \node_modules\svgtofont\lib\utils.js:233:29
    at Array.forEach (<anonymous>)
    at \node_modules\svgtofont\lib\utils.js:230:37
    at new Promise (<anonymous>)
    at createSvgSymbol (\node_modules\svgtofont\lib\utils.js:229:12)
    at exports.default (\node_modules\svgtofont\lib\index.js:84:43)

**Comment by maimai123** [comment]
我也遇到了这个情况，sketch导出的svg带有<?xml version="1.0" encoding="UTF-8"?>的前缀， 生成symbol.svg的时候会报错

**Comment by jaywcjlove** [comment]
@maimai123 Export SVG Files using sketch's SVGO Compressor plugin.

**Comment by Grapdevs** [comment]
so is there any alternative, to manage the same?

**Comment by Grapdevs** [comment]
> @maimai123 Export SVG Files using sketch's SVGO Compressor plugin.

Thnx https://github.com/svg/svgo , helped me a lot

**Comment by jaywcjlove** [comment]
https://www.sketch.com/extensions/plugins/svgo-compressor/
