### ISSUE TITLE
Error with Cheerio

### ISSUE THREAD

**Issue by bug145** [jaywcjlove/svgtofont#237]
I am encountering this error, which is likely why the CSS file is not being created. 

Here’s how I’m using it:
`
svgtofont({
    src: tempFolder,
    dist: dst,
    emptyDist: true,
    log: true,
    fontName: 'flux',
    css: false,
    svgicons2svgfont: {
      fixedWidth: true,
      centerHorizontally: true,
      normalize: true,
      fontHeight: 200,
    },
  })
`

Here is the error message:

`
SUCCESS SVG font successfully created!                                                                                                                                                      18:35:30
  ╰┈▶ C:\Users\user\projects\test\assets\.font\icons\font.svg
SUCCESS TTF font successfully created!                                                                                                                                                      18:35:31
  ╰┈▶ C:\Users\user\projects\test\assets\.font\icons\font.ttf
✔ Дополнительные иллюстрации подключены                                                                                                                                                    18:35:31   
SUCCESS EOT font successfully created!                                                                                                                                                      18:35:31  
  ╰┈▶ C:\Users\user\projects\test\assets\.font\icons\font.eot
SUCCESS WOFF font successfully created!                                                                                                                                                     18:35:31
  ╰┈▶ C:\Users\user\projects\test\assets\.font\icons\font.woff
✔ Favicon будет установлен из кэша                                                                                                                                                         18:35:32
SUCCESS WOFF2 font successfully created!                                                                                                                                                    18:35:32  
  ╰┈▶ C:\Users\user\projects\test\assets\.font\icons\font.woff2
SvgToFont:CLI:ERR: Cannot read properties of undefined (reading 'load')                                                                                                                     18:35:32  

  at createSvgSymbol (node_modules\svgtofont\lib\utils.js:236:33)
  at exports.default (node_modules\svgtofont\lib\index.js:123:43)
`

**Comment by marcos-castrillo** [comment]
I'm having the exact same error, it was working fine before. I'm using v4.2.2.

**Comment by skyerday** [comment]
cheerio 1.0.0 issue.
workaround:
rollback to 1.0.0-rc.12

Yarn
`
  "resolutions": {
    "cheerio": "1.0.0-rc.12"
  },
`

**Comment by jaywcjlove** [comment]
@skyerday @marcos-castrillo @bug145 

- https://github.com/jaywcjlove/svgtofont/issues/236

**Comment by jaywcjlove** [comment]
@skyerday @marcos-castrillo @bug145  Upgrade to `v5.0.3`
